version: "3"

services:
  web:
    image: docker.io/bierik/timeline-web
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
      platforms:
        - linux/amd64

  api:
    image: docker.io/bierik/timeline-api
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
      platforms:
        - linux/amd64
