services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5000:3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - 5002:8000
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: db
    image: postgres:16.3-alpine3.19
    ports:
      - 5001:5432
    volumes:
      - ./var/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
