version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5000:3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - 5002:8000
    environment:
      DJANGO_DATABASE_PASSWORD: postgres
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_USER: postgres
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: db
    image: postgres:16.1-alpine3.18
    ports:
      - 5001:5432
    volumes:
      - ./var/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
