version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:8000
    environment:
      DJANGO_DATABASE_PASSWORD: postgres
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_USER: postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16.1-alpine3.18
    ports:
      - 5001:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
