# Generated by Django 3.2.8 on 2022-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('date', models.DateField(verbose_name='Datum')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('icon', models.CharField(max_length=1, verbose_name='Icon')),
            ],
        ),
    ]
