# Generated by Django 3.2.14 on 2022-09-10 15:54

import django_editorjs_fields.fields
import django_extensions.db.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "description",
                    django_editorjs_fields.fields.EditorJsJSONField(null=True, verbose_name="Beschreibung"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=255, verbose_name="Icon"),
                ),
                (
                    "relations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reverse_relations",
                        to="events.Event",
                        verbose_name="Relationen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ereignis",
                "verbose_name_plural": "Ereignisse",
                "ordering": ["created"],
            },
        ),
    ]
