# Generated by Django 3.2.8 on 2022-01-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, max_length=1, verbose_name='Icon'),
        ),
    ]
