# Generated by Django 3.2.8 on 2022-02-23 21:08

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='relations',
            field=models.ManyToManyField(blank=True, to='events.Event', verbose_name='Relationen'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=sorl.thumbnail.fields.ImageField(upload_to='', verbose_name='Bilddatei'),
        ),
    ]
