FROM python:3.12.0-alpine3.18 as builder

WORKDIR /app

RUN apk add --no-cache gcc musl-dev postgresql-dev vips-dev

COPY requirements.txt .

RUN --mount=type=cache,target=/root/.cache \
    python -m pip install -r requirements.txt

FROM python:3.12.0-alpine3.18

RUN apk add --no-cache postgresql vips

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

WORKDIR /app

COPY ./docker/entrypoint.sh .

EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
