FROM python:3.12.4-alpine3.20 AS builder

WORKDIR /app

RUN apk add --no-cache gcc musl-dev postgresql-dev vips-dev

COPY poetry.lock pyproject.toml ./

RUN --mount=type=cache,target=/root/.cache \
    python -m pip install poetry==1.8.4 && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

FROM python:3.12.4-alpine3.20

RUN apk add --no-cache postgresql vips

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

WORKDIR /app

EXPOSE 8000
ENTRYPOINT ["/app/docker/entrypoint.sh"]

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
