# Generated by Django 3.2.14 on 2022-09-10 15:54

import django.db.models.deletion
import django_extensions.db.fields
import sorl.thumbnail.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "file",
                    sorl.thumbnail.fields.ImageField(upload_to="", verbose_name="Bilddatei"),
                ),
                ("width", models.PositiveIntegerField(blank=True, default=0)),
                ("height", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="events.event",
                        verbose_name="Ereignis",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="image",
                        to="people.person",
                        verbose_name="Ereignis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bild",
                "verbose_name_plural": "Bilder",
                "ordering": ["created"],
            },
        ),
    ]
