# Generated by Django 3.2.24 on 2024-05-05 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["created", "title"],
                "verbose_name": "Ereignis",
                "verbose_name_plural": "Ereignisse",
            },
        ),
    ]
