# Generated by Django 5.1.3 on 2024-11-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Beschreibung"),
        ),
    ]
